version: 2.1

jobs:
  build:
    docker:
      - image: haskell:9.4.3
    steps:
      - checkout
      - run:
          name: Build quality gate
          command: make build
      - run:
          name: Test quality gate
          command: make test
      - run:
          name: Clean build artifacts
          command: make clean

workflows:
  test:
    jobs:
      - build
